### ISSUE TITLE
ModuleNotFoundError: No module named 'selenium.webdriver.common

### ISSUE THREAD

**Issue by crxssrazr93** [JakeMaldonado/Linkedin-Lead-Generator#1]
I get this when I run tests.py. I suppressed the hunter and hubspot code blocks.

What is the suggested python version to be used?

```
Traceback (most recent call last):
  File "tests.py", line 1, in <module>
    from main import GenerateKindling, GenerateAccounts, LinkedInPod
  File "/home/crxssrazr93/Downloads/Compressed/Linkedin-Lead-Generator-master/main.py", line 8, in <module>
    from selenium_utilities import linkedin_account_scrape, linkedin_scrape, google_company_search, get_driver, linkedin_nav_headcount_scrape, linkedin_like_post, linkedin_account_domain, auto_connect
  File "/home/crxssrazr93/Downloads/Compressed/Linkedin-Lead-Generator-master/selenium_utilities.py", line 5, in <module>
    from selenium.webdriver.common.action_chains import ActionChains
ModuleNotFoundError: No module named 'selenium.webdriver.common'
```

**Comment by crxssrazr93** [comment]
For Linux users, 

Install Selenium, dnspython and tldextract via pip3,
Latest chromedriver from your package manager.

Update: I installed selenium via pip and it now shows a different error,

```
Traceback (most recent call last):
  File "tests.py", line 1, in <module>
    from main import GenerateKindling, GenerateAccounts, LinkedInPod
  File "/home/crxssrazr93/Downloads/Compressed/Linkedin-Lead-Generator-master/main.py", line 10, in <module>
    from credentials import POD_ACCOUNTS
ImportError: cannot import name 'POD_ACCOUNTS' from 'credentials' (/home/crxssrazr93/Downloads/Compressed/Linkedin-Lead-Generator-master/credentials.py)


```

**Comment by JakeMaldonado** [comment]
> Update: I installed selenium via pip and it now shows a different error,
> 
> ```
> Traceback (most recent call last):
>   File "tests.py", line 1, in <module>
>     from main import GenerateKindling, GenerateAccounts, LinkedInPod
>   File "/home/crxssrazr93/Downloads/Compressed/Linkedin-Lead-Generator-master/main.py", line 10, in <module>
>     from credentials import POD_ACCOUNTS
> ImportError: cannot import name 'POD_ACCOUNTS' from 'credentials' (/home/crxssrazr93/Downloads/Compressed/Linkedin-Lead-Generator-master/credentials.py)
> ```

The file is looking for POD_ACCOUNTS in credentials so try making your credentials.py look like this until I can update it.

HUBSPOT_API_KEY = ''
HUNTER_API_KEY = ''
KINDLING_API_KEY = ''
LINKEDIN_USERNAME = 'YOUR EMAIL'
LINKEDIN_PASSWORD = 'YOUR PASSWORD'

POD_ACCOUNTS = {
    "accounts": []
}

**Comment by JakeMaldonado** [comment]
> I get this when I run tests.py. I suppressed the hunter and hubspot code blocks.
> 
> What is the suggested python version to be used?
> 
> ```
> Traceback (most recent call last):
>   File "tests.py", line 1, in <module>
>     from main import GenerateKindling, GenerateAccounts, LinkedInPod
>   File "/home/crxssrazr93/Downloads/Compressed/Linkedin-Lead-Generator-master/main.py", line 8, in <module>
>     from selenium_utilities import linkedin_account_scrape, linkedin_scrape, google_company_search, get_driver, linkedin_nav_headcount_scrape, linkedin_like_post, linkedin_account_domain, auto_connect
>   File "/home/crxssrazr93/Downloads/Compressed/Linkedin-Lead-Generator-master/selenium_utilities.py", line 5, in <module>
>     from selenium.webdriver.common.action_chains import ActionChains
> ModuleNotFoundError: No module named 'selenium.webdriver.common'
> ```

This was made on Python 3.6 with selenium 3.9.0. Maybe that will fix the Module not found problem

**Comment by crxssrazr93** [comment]
> > I get this when I run tests.py. I suppressed the hunter and hubspot code blocks.
> > What is the suggested python version to be used?
> > ```
> > Traceback (most recent call last):
> >   File "tests.py", line 1, in <module>
> >     from main import GenerateKindling, GenerateAccounts, LinkedInPod
> >   File "/home/crxssrazr93/Downloads/Compressed/Linkedin-Lead-Generator-master/main.py", line 8, in <module>
> >     from selenium_utilities import linkedin_account_scrape, linkedin_scrape, google_company_search, get_driver, linkedin_nav_headcount_scrape, linkedin_like_post, linkedin_account_domain, auto_connect
> >   File "/home/crxssrazr93/Downloads/Compressed/Linkedin-Lead-Generator-master/selenium_utilities.py", line 5, in <module>
> >     from selenium.webdriver.common.action_chains import ActionChains
> > ModuleNotFoundError: No module named 'selenium.webdriver.common'
> > ```
> 
> This was made on Python 3.6 with selenium 3.9.0. Maybe that will fix the Module not found problem



> > Update: I installed selenium via pip and it now shows a different error,
> > ```
> > Traceback (most recent call last):
> >   File "tests.py", line 1, in <module>
> >     from main import GenerateKindling, GenerateAccounts, LinkedInPod
> >   File "/home/crxssrazr93/Downloads/Compressed/Linkedin-Lead-Generator-master/main.py", line 10, in <module>
> >     from credentials import POD_ACCOUNTS
> > ImportError: cannot import name 'POD_ACCOUNTS' from 'credentials' (/home/crxssrazr93/Downloads/Compressed/Linkedin-Lead-Generator-master/credentials.py)
> > ```
> 
> The file is looking for POD_ACCOUNTS in credentials so try making your credentials.py look like this until I can update it.
> 
> HUBSPOT_API_KEY = ''
> HUNTER_API_KEY = ''
> KINDLING_API_KEY = ''
> LINKEDIN_USERNAME = 'YOUR EMAIL'
> LINKEDIN_PASSWORD = 'YOUR PASSWORD'
> 
> POD_ACCOUNTS = {
> "accounts": []
> }

Thanks. It now runs.

Please remember to mention the below as requisites;

Selenium, dnspython and tldextract via pip3,
Latest chromedriver from your package manager.

**Comment by JakeMaldonado** [comment]
@crxssrazr93 awesome! Thanks, i'll add them to the readme
